#!/bin/bash

set -eu

ROOT_PATH=`pwd`
SOURCE_PATH=$ROOT_PATH/src
INSTALL_PATH=$ROOT_PATH/local/stow

STOW_VERSION=2.2.2
GIT_VERSION=2.12.2
PYTHON_VERSION=3.6.1
CMAKE_MAJOR_VERSION=3.8
CMAKE_MINOR_VERSION=0
CMAKE_VERSION=$CMAKE_MAJOR_VERSION.$CMAKE_MINOR_VERSION
ZSH_VERSION=5.3.1

STOW=$ROOT_PATH/bin/stow
GIT=$ROOT_PATH/local/bin/git

mkdir $SOURCE_PATH || true

